site_name: Lets Go Golfing! Wiki
site_url: https://nuclearwarhead55.github.io/Letsgogolfing/

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Quicksand
    code: Roboto Mono
  icon:
    logo: material/golf

extra_css:
  - styles/letsgo.css

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Patch Notes: updates.md
  # Add other top-level sections here as you create them, for example:
  # - Guides:
  #   - Gameplay Basics: guides/gameplay.md
  #   - Courses: guides/courses.md
  # - Community: community.md

# Copyright
copyright: Copyright &copy; 2024 t2g2

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Khtp323N6h
    - icon: fontawesome/brands/roblox
      link: https://www.roblox.com/games/16491648982
    # - icon: fontawesome/brands/roblox # If there's a relevant Roblox group/profile
    #   link: https://www.roblox.com/... 